name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      uses: ReactiveCircus/android-emulator-runner@v2.4.0
      with:
        api-level: 29
        script: ./gradlew connectedCheck
